"""Config facade backed by the current local/dev API module."""

from data.api.api import (
    BASE_DIR,
    HAND_MODEL_PATH,
    IDENTITY_DECISION_TIMEOUT_SEC,
    IDENTITY_MIN_REGISTER_SAMPLES,
    IDENTITY_MIN_VERIFY_SAMPLES,
    IDENTITY_SIM_THRESHOLD,
    MODEL_PATH,
    MYSQL_CONFIG,
    PHONE_MODEL_PATH,
    PHONE_YOLO_MODEL_PATH,
    SMOKING_MODEL_PATH,
    TELEGRAM_BOT_TOKEN,
    TELEGRAM_WEBHOOK_SECRET,
    app,
    socketio,
)

__all__ = [
    "app",
    "socketio",
    "BASE_DIR",
    "MODEL_PATH",
    "HAND_MODEL_PATH",
    "SMOKING_MODEL_PATH",
    "PHONE_MODEL_PATH",
    "PHONE_YOLO_MODEL_PATH",
    "MYSQL_CONFIG",
    "IDENTITY_SIM_THRESHOLD",
    "IDENTITY_MIN_REGISTER_SAMPLES",
    "IDENTITY_MIN_VERIFY_SAMPLES",
    "IDENTITY_DECISION_TIMEOUT_SEC",
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_WEBHOOK_SECRET",
]

